version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "8080:8080" # Expose WebSocket port
    environment:
      - WEBSOCKET_PORT=8080 # Optional: Explicitly set port for backend
    networks:
      - lava-monitor-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      args:
        # Pass the backend service hostname and port to the frontend build
        VITE_WS_URL: ws://localhost:8080
    ports:
      - "3000:80" # Expose Nginx port (access UI at http://localhost:3000)
    depends_on:
      backend:
        condition: service_healthy # Wait for backend healthcheck to pass
    networks:
      - lava-monitor-net

networks:
  lava-monitor-net:
    driver: bridge 